"""empty message

Revision ID: c37fc807ea4d
Revises: 0f86e55aa24a
Create Date: 2023-02-23 14:17:52.099803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37fc807ea4d'
down_revision = '0f86e55aa24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
